---
title: Jumichot.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Julien Michot
description: Ruby on Rails and Javascript developer
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: jumichot
  instagram: 
  linkedin: jumichot
  pinterest: 
  rss: 
  twitter: jumichot
  stackoverflow: 
disqus: 
google_analytics: UA-58805943-1
url: http://www.julienmichot.fr
baseurl: ''
markdown: kramdown
highlighter: pygments
permalink: "/:title/"
version: v1.0.0
sass:
  sass_dir: _scss
  style: :expanded
gems:
- jemoji
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
